### ISSUE TITLE
Wrong format

### ISSUE THREAD

**Issue by SamGG** [biosurf/CyTOF#1]
Hi,
Thanks for having brought back these invaluable primers.
I have a problem to load the RData file. Could you check?
Best.
```
> download.file("https://github.com/biosurf/CyTOF/raw/master/biosurf/cytof/live_2samples.Rdata", "live_2samples.Rdata")
trying URL 'https://github.com/biosurf/CyTOF/raw/master/biosurf/cytof/live_2samples.Rdata'
Content type 'application/octet-stream' length 2892068 bytes (2.8 MB)
downloaded 2.8 MB

> load("live_2samples.Rdata")
Error in load("live_2samples.Rdata") : 
  bad restore file magic number (file may be corrupted) -- no data loaded
In addition: Warning messages:
1: In readChar(con, 5L, useBytes = TRUE) :
  invalid or incomplete compressed data
2: file ‘live_2samples.Rdata’ has magic number ''
  Use of save versions prior to 2 is deprecated 
```

**Comment by cbligaard** [comment]
Hi Samuel,

Apologies for not noticing this issue sooner. This error arises due to the default save settings of different R versions - specifically versions before/after R 3.5.0. I.e. I can reproduce the issue with R v. 3.4.3 but not with R v. > 3.5.0.

I have now updated the .Rdata files to a version compatible with R < 3.5 as well. Hopefully this resolves the issue.

Best,
Christina
